### PR TITLE
Added responsive behavior

### PR DESCRIPTION
**Pull request by garciparedes**
The changes corresponds with simple replacement of `container` CSS class with `container-fluid`

- Before: 
Before

- After:
After

### CODE REVIEW

**Comment by benpence** [comment]
Hey @garciparedes, can you talk about the motivation for this? Were there elements that weren't displaying under the former bootstrap 'class'?

**Comment by garciparedes** [comment]
Hi @benpence! First of all I apologize for not adding an explanation of the changes. The old class `container` not works as responsive mode. So when the screen size isn't be a standard desktop the web content's size not properly fit to it. This behavior is fixed replacing this class by `container-fluid`, that adapts it width to the screen size. I have also modularised the footer of page in an external html to maintain code organised and prevent duplicates.

**Comment by benpence** [comment]
OK looks good to me. @garciparedes in the future, please make unrelated changes (container class, footer, stylesheet) in separate pull requests, as HTML changes are not very straightforward to review. Thanks!

**Comment by garciparedes** [comment]
Ok @benpence 🙂 . Many thanks for the advice. I'm CS undergraduate and this is one of my first contributions to an open source project so I appreciate any advice

**Pull request merged**
