### PR TITLE
Jillianc/remove-future-get

### PR DESCRIPTION
**Pull request by jcrossley**
Problem

Future.get in com.twitter.util is deprecated.

Solution

Replace Future.get in favor of Await.result

### CODE REVIEW

**Comment by kevinoliver** [comment]
@jcrossley lgtm. do you mind squashing it and then pushing it back?

**Comment by cacoco** [comment]
@jcrossley #ShipIt

**Comment by jcrossley** [comment]
Squashed!

**Comment by kevinoliver** [comment]
🚢  

i can merge it in this afternoon.

**Pull request merged**
