### PR TITLE
Fix css path

### PR DESCRIPTION
**Pull request by frankbo**
Currently styles or https://twitter.github.io/scala_school/ are not loaded.

The console throws a `not found` error when the browser wants to get the css files.

I changed the path from `/style.css` to `./style.css`. I wasn't able to deploy it with Jekyll on my local machine, but when changing the path in Chrome it worked fine.

### CODE REVIEW

**Comment by jvican** [comment]
Could someone give priority to this PR? The current scala school tutorial is naked and has no CSS, so it looks like a page from the 80s :smile:

**Comment by frankbo** [comment]
I saw today, that this one https://github.com/twitter/scala_school/pull/211 got merged.
For me the site is still broken. Can someone confirm that it works again, so that I can close the PR.

**Comment by rafaelmagu** [comment]
@frankbo this PR can be closed because the fix is already in master. The only thing missing is for Twitter team to deploy it.

**Comment by frankbo** [comment]
@rafaelmagu Thanks for the info. I just checked https://twitter.github.io/scala_school/ but when you say that only the deployment is just missing, but that it is in master I can definitely close the issue.

**Pull request closed without merging**
