### PR TITLE
Fix stylesheet paths. fix #204 #205

### LINKED ISSUE #204: https://twitter.github.io/scala_school/ lost its styling
https://github.com/twitter/scala_school/pull/202 was recently merged, after which I pulled from master and ran `make publish`, as the readme says. This deployed the latest version of the site except it lost all its styling in production. 

**Steps to reproduce:**
- request write access to this repository
- clone master and ensure the dependencies listed in the readme are installed
- run `make serve` to see the local site with the proper styling
- run `make publish` to see the production site without the styling

### PR DESCRIPTION
**Pull request by taverasmisael**
By removing the '/' at the beginning of styles URL in both post and default layout seem to solve the styles issues related to #204. In #205 is fixed but not in both layout files. I uploaded to my own GH-Page where you can see it working: https://taverasmisael.github.io/scala_school/

PD: I made these changes before realizing it was already a PR with these, but as seem on #204 the styles still not working.

### CODE REVIEW

**Comment by vincentfree** [comment]
Looks good again hope it gets excepted soon so the main page also gets its styling back

**Comment by agargenta** [comment]
Thanks @vincentfree!

**Comment by Kevin-Lee** [comment]
When can we have it released? It's still broken.

screen shot 2019-02-25 at 4 12 25 pm

**Comment by vincentfree** [comment]
Maybe someone needs to run a deploy script or something. Don't think a build had been triggert

**Pull request merged**
