### PR TITLE
Added Croatian translation - part one

### PR DESCRIPTION
**Pull request by boljsa**
Added Croatian translation - part one

### CODE REVIEW

**Comment by boljsa** [comment]
Should I close the pull request or someone else?
Who will review and merge this changes?
Thanks for the reply.

**Comment by benpence** [comment]
Hi @boljsa,

Thank you and good effort, but you've only translated the front page (`index.html`). I think it is premature to accept this pull request without at least one lesson (`basics.textile` for example).

Also, Croatian fluency is somewhat rare at Twitter internally so it's possible that we won't be able to find someone to review your changes.

**Comment by benpence** [comment]
Oh I didn't see your other pull request: #168 . I will continue discussion there

**Comment by boljsa** [comment]
Hi Ben,

Thank you for your response.
I will continue to translate files and add them to the pull request #168 if you agree.

Best regards,
Frank (boljsa)

**Pull request closed without merging**
